# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image_embedding.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='image_embedding.proto',
  package='image_embedding',
  syntax='proto3',
  serialized_pb=_b('\n\x15image_embedding.proto\x12\x0fimage_embedding\"\x1f\n\x10\x45mbeddingRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"&\n\x11\x45mbeddingResponse\x12\x11\n\tembedding\x18\x01 \x03(\x02\" \n\x11\x44imensionResponse\x12\x0b\n\x03\x64im\x18\x01 \x01(\x05\" \n\rSimpleReponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xf3\x01\n\x0eImageEmbedding\x12T\n\tEmbedding\x12!.image_embedding.EmbeddingRequest\x1a\".image_embedding.EmbeddingResponse\"\x00\x12I\n\tDimension\x12\x16.image_embedding.Empty\x1a\".image_embedding.DimensionResponse\"\x00\x12@\n\x04Info\x12\x16.image_embedding.Empty\x1a\x1e.image_embedding.SimpleReponse\"\x00\x62\x06proto3')
)




_EMBEDDINGREQUEST = _descriptor.Descriptor(
  name='EmbeddingRequest',
  full_name='image_embedding.EmbeddingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='image_embedding.EmbeddingRequest.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=73,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='image_embedding.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=82,
)


_EMBEDDINGRESPONSE = _descriptor.Descriptor(
  name='EmbeddingResponse',
  full_name='image_embedding.EmbeddingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='embedding', full_name='image_embedding.EmbeddingResponse.embedding', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=122,
)


_DIMENSIONRESPONSE = _descriptor.Descriptor(
  name='DimensionResponse',
  full_name='image_embedding.DimensionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dim', full_name='image_embedding.DimensionResponse.dim', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=156,
)


_SIMPLEREPONSE = _descriptor.Descriptor(
  name='SimpleReponse',
  full_name='image_embedding.SimpleReponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='image_embedding.SimpleReponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=190,
)

DESCRIPTOR.message_types_by_name['EmbeddingRequest'] = _EMBEDDINGREQUEST
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['EmbeddingResponse'] = _EMBEDDINGRESPONSE
DESCRIPTOR.message_types_by_name['DimensionResponse'] = _DIMENSIONRESPONSE
DESCRIPTOR.message_types_by_name['SimpleReponse'] = _SIMPLEREPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmbeddingRequest = _reflection.GeneratedProtocolMessageType('EmbeddingRequest', (_message.Message,), dict(
  DESCRIPTOR = _EMBEDDINGREQUEST,
  __module__ = 'image_embedding_pb2'
  # @@protoc_insertion_point(class_scope:image_embedding.EmbeddingRequest)
  ))
_sym_db.RegisterMessage(EmbeddingRequest)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'image_embedding_pb2'
  # @@protoc_insertion_point(class_scope:image_embedding.Empty)
  ))
_sym_db.RegisterMessage(Empty)

EmbeddingResponse = _reflection.GeneratedProtocolMessageType('EmbeddingResponse', (_message.Message,), dict(
  DESCRIPTOR = _EMBEDDINGRESPONSE,
  __module__ = 'image_embedding_pb2'
  # @@protoc_insertion_point(class_scope:image_embedding.EmbeddingResponse)
  ))
_sym_db.RegisterMessage(EmbeddingResponse)

DimensionResponse = _reflection.GeneratedProtocolMessageType('DimensionResponse', (_message.Message,), dict(
  DESCRIPTOR = _DIMENSIONRESPONSE,
  __module__ = 'image_embedding_pb2'
  # @@protoc_insertion_point(class_scope:image_embedding.DimensionResponse)
  ))
_sym_db.RegisterMessage(DimensionResponse)

SimpleReponse = _reflection.GeneratedProtocolMessageType('SimpleReponse', (_message.Message,), dict(
  DESCRIPTOR = _SIMPLEREPONSE,
  __module__ = 'image_embedding_pb2'
  # @@protoc_insertion_point(class_scope:image_embedding.SimpleReponse)
  ))
_sym_db.RegisterMessage(SimpleReponse)



_IMAGEEMBEDDING = _descriptor.ServiceDescriptor(
  name='ImageEmbedding',
  full_name='image_embedding.ImageEmbedding',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=193,
  serialized_end=436,
  methods=[
  _descriptor.MethodDescriptor(
    name='Embedding',
    full_name='image_embedding.ImageEmbedding.Embedding',
    index=0,
    containing_service=None,
    input_type=_EMBEDDINGREQUEST,
    output_type=_EMBEDDINGRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Dimension',
    full_name='image_embedding.ImageEmbedding.Dimension',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_DIMENSIONRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Info',
    full_name='image_embedding.ImageEmbedding.Info',
    index=2,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_SIMPLEREPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IMAGEEMBEDDING)

DESCRIPTOR.services_by_name['ImageEmbedding'] = _IMAGEEMBEDDING

# @@protoc_insertion_point(module_scope)
