# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image_embedding.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='image_embedding.proto',
  package='image_embedding',
  syntax='proto3',
  serialized_pb=_b('\n\x15image_embedding.proto\x12\x0fimage_embedding\"\x1f\n\x10\x45mbeddingRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"&\n\x11\x45mbeddingResponse\x12\x11\n\tembedding\x18\x01 \x03(\x02\" \n\x11\x44imensionResponse\x12\x0b\n\x03\x64im\x18\x01 \x01(\x05\x32\xb1\x01\n\x0eImageEmbedding\x12T\n\tEmbedding\x12!.image_embedding.EmbeddingRequest\x1a\".image_embedding.EmbeddingResponse\"\x00\x12I\n\tDimension\x12\x16.image_embedding.Empty\x1a\".image_embedding.DimensionResponse\"\x00\x62\x06proto3')
)




_EMBEDDINGREQUEST = _descriptor.Descriptor(
  name='EmbeddingRequest',
  full_name='image_embedding.EmbeddingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='image_embedding.EmbeddingRequest.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=73,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='image_embedding.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=82,
)


_EMBEDDINGRESPONSE = _descriptor.Descriptor(
  name='EmbeddingResponse',
  full_name='image_embedding.EmbeddingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='embedding', full_name='image_embedding.EmbeddingResponse.embedding', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=122,
)


_DIMENSIONRESPONSE = _descriptor.Descriptor(
  name='DimensionResponse',
  full_name='image_embedding.DimensionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dim', full_name='image_embedding.DimensionResponse.dim', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=156,
)

DESCRIPTOR.message_types_by_name['EmbeddingRequest'] = _EMBEDDINGREQUEST
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['EmbeddingResponse'] = _EMBEDDINGRESPONSE
DESCRIPTOR.message_types_by_name['DimensionResponse'] = _DIMENSIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmbeddingRequest = _reflection.GeneratedProtocolMessageType('EmbeddingRequest', (_message.Message,), dict(
  DESCRIPTOR = _EMBEDDINGREQUEST,
  __module__ = 'image_embedding_pb2'
  # @@protoc_insertion_point(class_scope:image_embedding.EmbeddingRequest)
  ))
_sym_db.RegisterMessage(EmbeddingRequest)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'image_embedding_pb2'
  # @@protoc_insertion_point(class_scope:image_embedding.Empty)
  ))
_sym_db.RegisterMessage(Empty)

EmbeddingResponse = _reflection.GeneratedProtocolMessageType('EmbeddingResponse', (_message.Message,), dict(
  DESCRIPTOR = _EMBEDDINGRESPONSE,
  __module__ = 'image_embedding_pb2'
  # @@protoc_insertion_point(class_scope:image_embedding.EmbeddingResponse)
  ))
_sym_db.RegisterMessage(EmbeddingResponse)

DimensionResponse = _reflection.GeneratedProtocolMessageType('DimensionResponse', (_message.Message,), dict(
  DESCRIPTOR = _DIMENSIONRESPONSE,
  __module__ = 'image_embedding_pb2'
  # @@protoc_insertion_point(class_scope:image_embedding.DimensionResponse)
  ))
_sym_db.RegisterMessage(DimensionResponse)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class ImageEmbeddingStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.Embedding = channel.unary_unary(
          '/image_embedding.ImageEmbedding/Embedding',
          request_serializer=EmbeddingRequest.SerializeToString,
          response_deserializer=EmbeddingResponse.FromString,
          )
      self.Dimension = channel.unary_unary(
          '/image_embedding.ImageEmbedding/Dimension',
          request_serializer=Empty.SerializeToString,
          response_deserializer=DimensionResponse.FromString,
          )


  class ImageEmbeddingServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def Embedding(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def Dimension(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_ImageEmbeddingServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Embedding': grpc.unary_unary_rpc_method_handler(
            servicer.Embedding,
            request_deserializer=EmbeddingRequest.FromString,
            response_serializer=EmbeddingResponse.SerializeToString,
        ),
        'Dimension': grpc.unary_unary_rpc_method_handler(
            servicer.Dimension,
            request_deserializer=Empty.FromString,
            response_serializer=DimensionResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'image_embedding.ImageEmbedding', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaImageEmbeddingServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def Embedding(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def Dimension(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaImageEmbeddingStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def Embedding(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    Embedding.future = None
    def Dimension(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    Dimension.future = None


  def beta_create_ImageEmbedding_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('image_embedding.ImageEmbedding', 'Dimension'): Empty.FromString,
      ('image_embedding.ImageEmbedding', 'Embedding'): EmbeddingRequest.FromString,
    }
    response_serializers = {
      ('image_embedding.ImageEmbedding', 'Dimension'): DimensionResponse.SerializeToString,
      ('image_embedding.ImageEmbedding', 'Embedding'): EmbeddingResponse.SerializeToString,
    }
    method_implementations = {
      ('image_embedding.ImageEmbedding', 'Dimension'): face_utilities.unary_unary_inline(servicer.Dimension),
      ('image_embedding.ImageEmbedding', 'Embedding'): face_utilities.unary_unary_inline(servicer.Embedding),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_ImageEmbedding_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('image_embedding.ImageEmbedding', 'Dimension'): Empty.SerializeToString,
      ('image_embedding.ImageEmbedding', 'Embedding'): EmbeddingRequest.SerializeToString,
    }
    response_deserializers = {
      ('image_embedding.ImageEmbedding', 'Dimension'): DimensionResponse.FromString,
      ('image_embedding.ImageEmbedding', 'Embedding'): EmbeddingResponse.FromString,
    }
    cardinalities = {
      'Dimension': cardinality.Cardinality.UNARY_UNARY,
      'Embedding': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'image_embedding.ImageEmbedding', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
