# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import image_embedding_pb2 as image__embedding__pb2


class ImageEmbeddingStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Embedding = channel.unary_unary(
        '/image_embedding.ImageEmbedding/Embedding',
        request_serializer=image__embedding__pb2.EmbeddingRequest.SerializeToString,
        response_deserializer=image__embedding__pb2.EmbeddingResponse.FromString,
        )
    self.Dimension = channel.unary_unary(
        '/image_embedding.ImageEmbedding/Dimension',
        request_serializer=image__embedding__pb2.Empty.SerializeToString,
        response_deserializer=image__embedding__pb2.DimensionResponse.FromString,
        )
    self.Info = channel.unary_unary(
        '/image_embedding.ImageEmbedding/Info',
        request_serializer=image__embedding__pb2.Empty.SerializeToString,
        response_deserializer=image__embedding__pb2.SimpleReponse.FromString,
        )


class ImageEmbeddingServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Embedding(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Dimension(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Info(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ImageEmbeddingServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Embedding': grpc.unary_unary_rpc_method_handler(
          servicer.Embedding,
          request_deserializer=image__embedding__pb2.EmbeddingRequest.FromString,
          response_serializer=image__embedding__pb2.EmbeddingResponse.SerializeToString,
      ),
      'Dimension': grpc.unary_unary_rpc_method_handler(
          servicer.Dimension,
          request_deserializer=image__embedding__pb2.Empty.FromString,
          response_serializer=image__embedding__pb2.DimensionResponse.SerializeToString,
      ),
      'Info': grpc.unary_unary_rpc_method_handler(
          servicer.Info,
          request_deserializer=image__embedding__pb2.Empty.FromString,
          response_serializer=image__embedding__pb2.SimpleReponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'image_embedding.ImageEmbedding', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
