#!/bin/bash
source config.sh
ROOT="$(pwd)/$(dirname "$0")"
MODEL="inception_v4"

mkdir -p "${ROOT}/embeddings"
mkdir -p "${ROOT}/models"
mkdir -p "${ROOT}/log"

docker run -d --name $CONTAINER_NAME -it -p $PORT:50051 \
         -v "${ROOT}/log":/app/log \
         --volumes-from aws-config \
         --network daangn-net \
         daangn/faiss-image-server server.py --log "log/${CONTAINER_NAME}.log" \
           --save_filepath s3://daangn/ml/test/models/faiss-image-server.index \
           --remote_embedding_host "image-embedding-server:50051" \
           --lb \
           --debug
